name: FactionsXL
main: de.erethon.factionsxl.FactionsXL
version: ${project.version}${buildNo}
authors: [Daniel Saukel, Malfrador]
description: ${project.description}
website: ${project.url}
softdepend: [Vault, LWC, Dynmap, HolographicDisplays, Cannons]
api-version: 1.13
commands:
  factionsxl:
    description: Reference command for FactionsXL.
    aliases: [fxl,f,faction]
  home:
    description: Alias for /f playerHome.
  setHome:
    description: Alias for /f setPlayerHome.
